[package]
name = "add"
version = "0.0.1"
authors = [
    "Volt Contributors (https://github.com/voltpkg/volt/graphs/contributors)",
]
description = "The add command for volt cli."
edition = "2018"

[dependencies]
async-trait = "0.1"
colored = "2.0"
futures = "0.3"
indicatif = "0.16"
tokio = { version = "*", features = ["rt-multi-thread"] }
volt_core = { path = "../volt_core" }
init = { path = "../init" }
utils = { path = "../utils" }
miette = "1.0.1"
