[package]
name = "add"
version = "0.0.1"
authors = ["Volt Contributors (https://github.com/voltpkg/volt/graphs/contributors)"]
description = "The add command for volt cli."
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
colored = "2.0"
futures = "0.3"
indicatif = "0.16"
smol = "1.2.5"
volt_core = { path = "../volt_core" }
init = { path = "../init" }
utils = { path="../utils" }