[workspace]
members = [
  "src/volt",
  "src/add",
  "src/cache",
  "src/clone",
  "src/compress",
  "src/volt_core",
  "src/create",
  "src/deploy",
  "src/help",
  "src/init",
  "src/install",
  "src/utils",
  "src/list",
  "src/migrate",
  "src/remove",
  "src/run",
  "src/scripts",
  "src/fix",
  "src/watch",
  "src/update",
  "src/set",
  "src/audit",
  "src/check",
  "src/info",
  "src/search",
  "src/outdated",
  "src/login",
  "src/logout",
  "src/publish",
  "src/tag",
  "src/owner",
  "src/team",
  "src/stat",
  "src/rslint/rslint_parser",
  "src/rslint/rslint_errors",
  "src/rslint/rslint_lexer",
  "src/rslint/rslint_rowan",
  "src/rslint/rslint_syntax",
  "src/rslint/rslint_core",
  "src/rslint/rslint_macros",
  "src/rslint/rslint_lsp",
  "src/rslint/rslint_regex",
  "src/rslint/rslint_text_edit",
  "src/rslint/rslint_config",
  "src/rslint/rslint_cli",
]

exclude = [
  "src/prototype/compress",
  "src/prototype/syntax",
  "platforms/cargo",
  "prototype/bincode-server",
  "server",
]


[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
panic = 'abort'
