[workspace]
members = [
  "src/volt",
  "src/volt_core",
  "src/rslint/rslint_parser",
  "src/rslint/rslint_errors",
  "src/rslint/rslint_lexer",
  "src/rslint/rslint_rowan",
  "src/rslint/rslint_syntax",
  "src/rslint/rslint_core",
  "src/rslint/rslint_macros",
  "src/rslint/rslint_regex",
  "src/rslint/rslint_text_edit",
  "src/rslint/rslint_config",
  "src/rslint/rslint_cli",
]

exclude = [
  "src/prototype/compress",
  "src/prototype/syntax",
  "registry",
  "platforms/cargo",
  "prototype/bincode-server",
  "server",
]


[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
panic = 'abort'
