[package]
name = "compress"
version = "0.0.1"
authors = [
    "Volt Contributors (https://github.com/voltpkg/volt/graphs/contributors)",
]
description = "The compress command for volt cli."
edition = "2018"

[dependencies]
miette = "1.0.1"
async-trait = "0.1"
colored = "2.0"
volt_core = { path = "../volt_core" }
utils = { path = "../utils" }
