[package]
name = "utils"
version = "0.1.0"
authors = ["Volt Contributors (https://github.com/voltpkg/volt/contributors)"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
chttp = "0.5.5"
anyhow = "1.0"
async-trait = "0.1"
reqwest = "0.11.4"
colored = "2.0"
console = "0.14"
dialoguer = "0.8"
dirs = "3.0"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha-1 = "0.9"
structopt = "0.3"
tar = "0.4"
thiserror = "1.0"
tokio = { version = "*", features = ["fs"] }
indicatif = "0.16"
bytes = "1.0.1"
walkdir = "2.3.2"
futures-util = "0.3.15"
rand = "0.8.4"
futures = "0.3.15"
semver_rs = "0.1.3"
lz4 = "1.23.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "errhandlingapi",
    "fileapi",
    "guiddef",
    "handleapi",
    "ioapiset",
    "processthreadsapi",
    "securitybaseapi",
    "winbase",
    "winioctl",
    "winnt",
] }
tempfile = "3.2"
scopeguard = "1.1"
