[package]
name = "volt"
version = "0.0.1"
authors = [
  "Volt Contributors (https://github.com/voltpkg/volt/graphs/contributors)",
]
description = "A fast, memory-safe package manager for the web."
edition = "2018"
default-run = "volt"

[dependencies]
async-trait = "0.1"
bat = "0.18.2"
clap = { git = "https://github.com/clap-rs/clap" }
colored = "2.0"
dialoguer = "0.8"
flate2 = "1.0"
futures = "0.3"
indicatif = "0.16"
isahc = "1.4.0"
miette = "1.0.1"
prettytable-rs = "0.8.0"
regex = "1"
reqwest = "0.11.4"
serde_json = "1.0.64"
serde = { version = "1.0", features = ["derive"] }
syntect = "4.5.0"
tar = "0.4"
termimad = "0.14.2"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }
utils = { path = "../utils" }
volt_core = { path = "../volt_core" }
walkdir = "2.3.2"
rslint_parser = { path = "../rslint/rslint_parser" }
