[package]
edition = "2018"
name = "rslint_parser"
version = "0.2.1"
authors = ["RDambrosio016 <rdambrosio016@gmail.com>"]
license = "MIT"
description = "An extremely fast ECMAScript parser made for the rslint project"
repository = "https://github.com/rslint/rslint"

[dependencies]
rslint_errors = { path = "../errors", version = "0.1.0" }
rslint_syntax = { path = "../syntax", version = "0.1" }
rslint_lexer = { path = "../lexer", version = "0.1", features = ["highlight"] }
rslint_rowan = { path = "../rowan", version = "0.10.0" }
num-bigint = "0.3.0"
lexical = { version = "5.2.0", features = ["radix"] }

[dev-dependencies]
expect-test = "1.0"
